### PR TITLE
Enabled readout of last 30 Charge Sessions from Wallbox; "setenergy" state enabled

### PR DESCRIPTION
**Pull request by Jarves020**
- Enabled the readout of the last 30 Charge Sessions from Wallbox. (report101 - report130)
  Values are Stored under new "Sessions" directory, including the RAW Json String for each Session.
- Enabled "setenergy" State to Transmit a Charging Goal in Wh to Wallbox if a number is entered.
- Updated Changelog

Changes Tested on a BMW Wallbox Connect (similar to KEBA P30x).

### CODE REVIEW

**Comment by jwiesel** [comment]
Hi @Jarves020 ,
I just tried to install the new version you provided (via url: https://github.com/Jarves020/ioBroker.kecontact/tarball/master)
Unfortunately I get an exception during install:

> Fertig mit Fehler: internal/modules/cjs/loader.js:1052 throw err; ^SyntaxError: /opt/iobroker/node_modules/iobroker.kecontact/io-package.json: Unexpected token s in JSON at position 3376 at parse () at Object.Module._extensions..json (internal/modules/cjs/loader.js:1049:22) at Module.load (internal/modules/cjs/loader.js:879:32) at Function.Module._load (internal/modules/cjs/loader.js:724:14) at Module.require (internal/modules/cjs/loader.js:903:19) at require (internal/modules/cjs/helpers.js:74:18) at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:481:19) at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1781:24 at ChildProcess. (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:478:47) at ChildProcess.emit (events.js:314:20)

Hence the installation got aborted with error code 1.

I assume your version comment referencing to **"setenergy"** should use single quotes instead of double quotes

> "en": "Added readout of last 30 Charging Sessions from Wallbox; Enabled "setenergy" State to send and set Charging Goal in Wh to Wallbox",
> "de": "Auslesen der letzten 30 Ladesessions aus Wallbox hinzugefügt; "setenergy" Wert zum setzen eines Ladeziels in Wh in der Wallbox aktiviert"

I can continue testing after your fix. :-)

**Comment by Jarves020** [comment]
Hi @jwiesel,

thx for the hint with the quotes.
The comment was the last thing i changed before creating the Pull request.
Thought i tested it....

I changed the double quotes to single quotes and updated the Adapter from Github on my Iobroker installation.
Problem should be solved...
Please test again, when you have time!

**Comment by jwiesel** [comment]
Hi @Jarves020,
thanks for the swift update! Now the installation worked.
Please find below my observations during testing:
Data
* The json entry in below the Sessions does not contain the correct values. It seems like they are cut after the first comma, or that the comma is shifted behind the last value: e.g. E-Pres shows: "2085,9 Wh", whereas the E-Pres value in json shows "20859,"
* Sometimes E-Pres shows values with a lot of decimals. e.g. "424.90000000000003 Wh" (json value in that case: "4249,"
* In some older sessions "ended" and "started" do not show a date-time, but the value of ended_s/started_s with three trailing "0" values (e.g. ended: 5615208000, ended_s: 5615208, started: 5471426000, stated_s: 5471426) --> dates in 1970 --> in younger sessions it seems ok (maybe due to my KEBA firmware update)

Usability:
* To make lives of users, who did not read the wallbox api reference easier, it would be great to add a description for the entries in the session-folders like you did it for SetEnergy to explain what the fields are about (e.g. E-Pres)
* Maybe we could use the same variable ids and roles for the sessions like in the main folder (e.g. "e_pres" - "text" vs. "ePres" - "value"). below Sessions you mostly use role "text"
* (minor detail): Naming convention of ids. So far in keyConnect every id uses camelCase starting with a small letter with no underscores. The new version partly contains capital letters in the beginning and underscores (e.g. "Sessions",  "e_pres", "AuthON")

Hope that helps!

**Comment by Jarves020** [comment]
Hi,

made some Changes:

Data:
- The Json Data Field represents the RAW Data recieved from the Box and contains the unedited Values! Some Values are transmitted in 0.1 Resolution from the Box and must be devided by 10. Because this is a RAW Data Field no changes or calculations are made here to the Data. 
- The lot of Decimals in some Values are caused by Javascripts "parseFloat Round error". This behaviour is also present in previous Adapter Versions. But i've now integrated a Workaround for this.
- Date Values Depend on TimeSync ("TimeQ" Value) of your Box. If no Time is set or not synchronized, then it Counts the Time from last System Restart upwards.

Useability:
-  Description was already there in the "desc" Field. Now i added a Description into the Name Data Field.
- Changed Variable ID's and Roles. The previous ID Naming were meant to match the API Documentation for easier referencing.
- Changed some ID Names to lower case Letter and removed underscores.

You can test again, if you like....

**Comment by jwiesel** [comment]
Thanks for all the updates you made @Jarves020 !
I just tested the latest version and it looks very good to me!
@UncleSamSwiss : Can you please merge?

**Pull request merged**
